version: '2.3'

services:
  jupyter:
    build: .
    ports:
      - 8888:8888
    volumes:
      - ./notebooks:/workspace/notebooks
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ "gpu" ]
    command: jupyter lab --no-browser --ip=0.0.0.0 --allow-root --ServerApp.disable_check_xsrf=true  --ServerApp.root_dir=/workspace --ServerApp.token='' --ServerApp.password=''
